# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # General Vagrant VM configuration
    config.vm.box = "centos/7"

    # my test server
    config.vm.define "my-server" do |server|
        server.vm.hostname = "my-server"
        config.vm.network "private_network", ip: "192.168.60.101", name: "vboxnet4"
    end

    config.vm.provider "virtualbox" do |vb|
      vb.name = "provision_ansible"
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = "2"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end
end